### ISSUE TITLE
Files: steg.pdf for accelerator missing

### ISSUE THREAD

**Issue by abpolym** [EasyCTF/easyctf-2015-writeups#65]
Hey,

steg.pdf for the task accelerator is missing. Can you please upload it? Thanks!

**Comment by mzhang28** [comment]
Sorry about that; it was too large to be uploaded to Gitbook. I added a link in [this commit](https://github.com/EasyCTF/easyctf-2015-writeups/commit/4fe070e8e5836086afc168fa25125cdc6ecc3160).
